### ISSUE TITLE
Create new SQL Table/Create Route Page

### ISSUE THREAD

**Issue by awurster1** [Speed-Router/speedrouter.run#1]
It might be wise to create a new SQL table that holds the individual routes. Then when we create the routes page, each link on the routes page can be an entry in the table. In many ways, the routes page will look identical to the games page (- the photo thumbnails). @d4rkd0s

**Comment by d4rkd0s** [comment]
@awurster1 this already exists 😄 see: https://github.com/Speed-Router/speedrouter.run/blob/master/database/migrations/2017_01_15_062415_create_routes_table.php

**Comment by d4rkd0s** [comment]
As for making the page, I am in the process of finishing the routes, strats, and runs pages.

**Comment by d4rkd0s** [comment]
This is complete!
